Controllers/DropcarController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rent_a_ride.Controllers
{
    public class DropcarController : Controller
    {
        RentaRidedbEntities2 db = new RentaRidedbEntities2();
        // GET: dropbike
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Droppedcar()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult Save4(Dropcar recar)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Dropcars.Add(recar);
        //        var car = db.CarRegisters.SingleOrDefault(e => e.CarNum == recar.CarNumber);
        //        if (car == null)
        //            return HttpNotFound("Bike number not found");
        //        car.Available = "yes";
        //        db.Entry(car).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }



        //    return View(recar);
        //}

        [HttpPost]
        public ActionResult Save(Dropcar recar)
        {
            if (ModelState.IsValid)
            {
                db.Dropcars.Add(recar);
                var car = db.CarRegisters.SingleOrDefault(e => e.CarNum == recar.CarNumber);
                if (car == null)
                    return HttpNotFound("Car Number is not valid");
                car.Available = "yes";
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recar);
        }






        [HttpPost]

        public ActionResult Getid(string CarNumber)
        {
            var carN = (from s in db.CarRents
                         where s.CarId == CarNumber
                         select new
                         {
                             Start_Date = s.StartDate,
                             End_Date = s.EndDate,
                             Cusid = s.CustomerId,
                             Carnum = s.CarId,
                             Fee_ = s.Fee,
                             ElapsedDays = SqlFunctions.DateDiff("day", s.EndDate, DateTime.Now)
                         }).ToArray();

            return Json(carN, JsonRequestBehavior.AllowGet);
        }



    }
}

Controllers/RentbikeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rent_a_ride.Controllers
{
    public class RentbikeController : Controller
    {
        RentaRidedbEntities2 db = new RentaRidedbEntities2();

        // GET: Rentbike
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Getbike()
        {
            var bike = db.BikeRegisters.ToList();
            return Json(bike, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Getid(int id)
        {
            var customer = (from s in db.Customers where s.CustomerId == id select s.CustomerName).ToList();
            return Json(customer, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Getavil(String BikeNum)
        {
            var bikeavil = (from s in db.BikeRegisters where s.BikeNum == BikeNum select s.Available).FirstOrDefault();
            return Json(bikeavil, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult Save(BikeRent rent)
        {
            if(ModelState.IsValid)
            {
                db.BikeRents.Add(rent);
                var bike = db.BikeRegisters.SingleOrDefault(e => e.BikeNum == rent.BikeId);
                if (bike == null)
                    return HttpNotFound("Bike Number is not valid");
                bike.Available = "no";
                db.Entry(bike).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rent);
        }


    }   
}

Controllers/RentcarController.cs
using Rent_a_ride.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rent_a_ride.Controllers
{
    public class RentcarController : Controller
    {

        RentaRidedbEntities2 db = new RentaRidedbEntities2();
        // GET: Rentcar
        public ActionResult Index()
        {
            var result = (from r in db.CarRents
                          join c in db.CarRegisters on r.CarId equals c.CarNum

                          select new RentViewModel
                          {
                              Id = r.Id,
                              CarId = r.CarId,
                              CustomerId=r.CustomerId,
                              Fee=r.Fee,
                              StartDate=r.StartDate,
                              EndDate=r.EndDate,
                              Available=c.Available


                          }).ToList();
            return View(result);
        }





        //[HttpGet]
        //public ActionResult Getbike()
        //{
        //    var bike = db.BikeRegisters.ToList();
        //    return Json(bike, JsonRequestBehavior.AllowGet);
        //}


        [HttpGet]
        public ActionResult Getcar()
        {
            var car = db.CarRegisters.ToList();
            return Json(car, JsonRequestBehavior.AllowGet);
        }





        //[HttpPost]
        //public ActionResult Getid(int id)
        //{
        //    var customer = (from s in db.Customers where s.CustomerId == id select s.CustomerName).ToList();
        //    return Json(customer, JsonRequestBehavior.AllowGet);
        //}


        [HttpPost]
        public ActionResult Getid(int id)
        {
            var customer = (from s in db.Customers where s.CustomerId == id select s.CustomerName).ToList();
            return Json(customer, JsonRequestBehavior.AllowGet);
        }




        //[HttpPost]
        //public ActionResult Getavil(String BikeNum)
        //{
        //    var bikeavil = (from s in db.BikeRegisters where s.BikeNum == BikeNum select s.Available).FirstOrDefault();
        //    return Json(bikeavil, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public ActionResult Getavil(String CarNum)
        {
            var caravil = (from s in db.CarRegisters where s.CarNum == CarNum select s.Available).FirstOrDefault();
            return Json(caravil, JsonRequestBehavior.AllowGet);
        }




        //[HttpPost]
        //public ActionResult Save(BikeRent rent)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.BikeRents.Add(rent);
        //        var bike = db.BikeRegisters.SingleOrDefault(e => e.BikeNum == rent.BikeId);
        //        if (bike == null)
        //            return HttpNotFound("Bike Number is not valid");
        //        bike.Available = "no";
        //        db.Entry(bike).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(rent);
        //}


        [HttpPost]
        public ActionResult Save(CarRent rent)
        {

            if (ModelState.IsValid)
            {
                db.CarRents.Add(rent);
                var car = db.CarRegisters.SingleOrDefault(e => e.CarNum == rent.CarId);
                if (car == null)
                    return HttpNotFound("Entered car number is Invalid");
                car.Available = "no";
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rent);
        }






    }
}

Controllers/dropbikeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rent_a_ride.Controllers
{
    public class dropbikeController : Controller
    {
        RentaRidedbEntities2 db = new RentaRidedbEntities2();
        // GET: dropbike
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Droppedbike()
        {
            return View();
        }


        //[HttpPost]
        public ActionResult Save(Dropbike rebike)
        {
            if(ModelState.IsValid)
            {
                db.Dropbikes.Add(rebike);
                var bike = db.BikeRegisters.SingleOrDefault(e => e.BikeNum == rebike.BikeNumber);
                if (bike == null)
                    return HttpNotFound("Bike number not found");
                bike.Available = "yes";
                db.Entry(bike).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }



            return View(rebike);
        }







        [HttpPost]

        public ActionResult Getid(string BikeNumber)
        {
            var bikeN = (from s in db.BikeRents
                         where s.BikeId == BikeNumber
                         select new
                         {
                             Start_Date = s.StartDate,
                             End_Date = s.EndDate,
                             Cusid = s.CustomerId,
                             Bikenum = s.BikeId,
                             Fee_ = s.Fee,
                             ElapsedDays =SqlFunctions.DateDiff("day",s.EndDate,DateTime.Now)
                         }).ToArray();

            return Json(bikeN, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/PartialView.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body background="~/Content/l.jpg">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*                @Html.ActionLink("Rent a Ride System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                *@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                    <li>@Html.ActionLink("Register/Login", "Register", "UserRegister")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body background="~/Content/l.jpg">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
@*                @Html.ActionLink("Rent a Ride System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
*@            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   @* <li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("FourWheeler", "Index", "CarRegisters")</li>
                    <li>@Html.ActionLink("TwoWheeler", "Index", "BikeRegisters")</li>
                    <li>@Html.ActionLink("Customer Details", "Index", "Customers")</li>
                    <li>@Html.ActionLink("CarRent", "Index", "Rentcar")</li>
                    <li>@Html.ActionLink("BikeRent", "Index", "Rentbike")</li>
                    <li>@Html.ActionLink("Returncar", "Index", "Dropcar")</li>
                    <li>@Html.ActionLink("Returnbike", "Index", "dropbike")</li>                   
                    <li>@Html.ActionLink("Logout", "Logout", "UserRegister")</li>
                    </ul>
</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()   
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>