Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rent_a_ride.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Home()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/UserRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rent_a_ride.Controllers
{
    public class UserRegisterController : Controller
    {

        RentaRidedbEntities2 db = new RentaRidedbEntities2();

        // GET: UserRegister
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Register(Register reg)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    db.Registers.Add(reg);
                    db.SaveChanges();
                    return View("Login");
                }
                catch (Exception)
                {
                    ViewBag.Messageone("Registration not successful");
                    // Response.Write("<script>alert(\"an error occur while registration\")</script>");
                    return RedirectToAction("Register", "UserController");
                }
            }

            return RedirectToAction("Login");
        }


        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }





        [HttpPost]
        public ActionResult Login(Register ui)
        {
          
                try
                {
                    Register u = db.Registers.Where(x => x.Username == ui.Username && x.Userpassword == ui.Userpassword).SingleOrDefault();
                    Session["UserID"] = u.UserID;
                    if (u.role == "Admin")
                    {
                        //  Session["UserID"] = u.UserID;

                        //if (Session["UserID"] == null)
                        //{
                        //    return RedirectToAction("Login");
                        //}
                        return RedirectToAction("Index", "Customers");
                    }
                    else
                    {
                        return RedirectToAction("Index", "CarRegisters");
                        //ViewBag.Message = "Invalid Password or Email Id";
                    }

                }

                catch (Exception e)
                {
                    ViewBag.ErrorMessage = "Please select an option" + e.Message;
                    return RedirectToAction("Register");
                }


        }


            public ActionResult Logout()
            {
                Session.Abandon();
                Session.RemoveAll();
                return RedirectToAction("Register");
            }

        }
    }

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "/Views/Shared/PartialView.cshtml";
}

<p style="font-size: 90px"> Rent a Ride</p>


@using (Html.BeginForm())
{

    @Html.ActionLink("Register or Login", "Index", "UserRegister")

    <!--@Html.AntiForgeryToken()

    <div class="registerBox">
        <h2 id="heading">Register</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <style>
            #submitButton {
                border: none;
                outline: none;
                height: 40px;
                background-color: grey;
                color: whitesmoke;
                font-size: 15px;
                border-radius: 20px;
                font-family: Arial, Helvetica, sans-serif;
                border: 1px solid whitesmoke;
                width: 100%;
            }

                #submitButton:hover {
                    cursor: pointer;
                    background-color: dodgerblue;
                }
            .box {
                background-color: lightgrey;
                width: 300px;
                border: 5px black;
                padding: 50px;
                margin: 20px;
            }
        </style>

        <center>
            <div class="box">
                <div class="form-group">


                    <div class="form-group">
                        <label class="form-label">UserID</label>
                        <input type="text" id="UserID" name="UserID" class="form-control" placeholder="Enter UserId" required>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Username</label>
                        <input type="text" id="Username" name="Username" class="form-control" placeholder="Enter username" required>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Password</label>
                        <input type="text" id="Userpassword" name="Userpassword" class="form-control" placeholder="Enter password" required>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Role</label>
                        <input type="text" id="role" name="role" class="form-control" placeholder="Admin or Customer ???" required>
                    </div>
                    <br />
                    <div id="navlink">
                        @Html.ActionLink("Already Registered ? LogIn", "Login", "UserRegister")
                    </div>
                </div>

                <center>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Register" class="btn btn-default" id="submitButton" />
                        </div>
                    </div>
               </center>
                </div>
    </center>
        <br />-->

    @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" id="submitButton"/>
            </div>
        </div>*@
    @*   <center>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-default" id="submitButton" />
                </div>
            </div>
        </center>*@
    <!--</div>-->

    @*  <br />
        <div id="navlink">
            @Html.ActionLink("Already Registered ? LogIn", "Login", "LoginEmployee")
        </div>*@
    <!--<br />
    <div id="errorMessage">
        @ViewBag.Message
        @ViewBag.after
    </div>-->

}




<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>